### ISSUE TITLE
[FEATURE] Additional configurations not handled by the proxmox module

### ISSUE THREAD

**Issue by santiagomr** [UdelaRInterior/ansible-role-proxmox-create-lxc#8]
When trying to modify container configuration files using a task with `lineinfile` or `blockinfile`, similar to [this](https://github.com/UdelaRInterior/ansible-role-proxmox-create-lxc/blob/caee7e0b0e7d3d0de472628ce6099d9862318d21/tasks/tun_interface.yml) discussed in #7, the following privilege error is obtained, even though the tasks are executed as root:
```
TASK [proxmox_create_lxc : Additional configurations] ********************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 1] Operación no permitida: '/etc/pve/nodes/node/lxc/.ansible_tmpa_wyTF132.conf'
fatal: [container.interior.edu.uy -> node.interior.edu.uy]: FAILED! => {"changed": false, "msg": "Failed to replace file: /home/deploy/.ansible/tmp/ansible-tmp-1569864350.97-58668108582440/tmp37vByR to /etc/pve/nodes/node/lxc/132.conf: [Errno 1] Operación no permitida: '/etc/pve/nodes/node/lxc/.ansible_tmpa_wyTF132.conf'"}

PLAY RECAP ***********************************************************************************************************************************************************************************
container.interior.edu.uy     : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

It would be useful to determine why this error is generated, using these modules is the correct way to manipulate configuration files.

**Comment by santiagomr** [comment]
In [v2.1.0](https://github.com/UdelaRInterior/ansible-role-proxmox-create-lxc/tree/v2.1.0) a workaround was introduced to implement this feature when the container is created, using the `pve_additional_conf` list  and `shell` module.

**Comment by kusold** [comment]
When you modify the lxc conf with `lineinfile`, you need to use [unsafe_writes](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html#parameter-unsafe_writes) so that the file is editted in place.

```
- name: set apparmor profile for container
  lineinfile:
    path: "/etc/pve/lxc/{{ proxmox_vm_id }}.conf"
    regexp: '^lxc.apparmor.profile:'
    line: "lxc.apparmor.profile: {{ apparmor_profile }}"
    unsafe_writes: yes # Otherwise proxmox denies permission
```
